create table tm_automoviles (client_rol_id integer not null, model_brand_id integer not null, license_plate varchar(8) not null, primary key (model_brand_id)) engine=InnoDB;
create table tm_marcas (id integer not null, name varchar(32) not null, primary key (id)) engine=InnoDB;
create table tm_marcas_seq (next_val bigint) engine=InnoDB;
insert into tm_marcas_seq values ( 1 );
create table tm_modelos (brand_id integer not null, year integer not null, name varchar(32) not null, primary key (brand_id)) engine=InnoDB;
create table tm_personas (dni integer not null, rol_id integer not null, street_number integer, name varchar(32) not null, phone_number varchar(32), sur_name varchar(32) not null, email varchar(64), street varchar(255), primary key (rol_id)) engine=InnoDB;
create table tm_roles (id integer not null, name varchar(32) not null, primary key (id)) engine=InnoDB;
create table tm_roles_seq (next_val bigint) engine=InnoDB;
insert into tm_roles_seq values ( 1 );
alter table tm_automoviles add constraint UK_n9yhw1oi4ovvufort6w5qxylo unique (client_rol_id);
alter table tm_personas add constraint UK_n0eje0x7n0wf8ojp2n81k07i unique (dni);
alter table tm_automoviles add constraint FKiwh0wecmhp1u7d7p2u4yob9y4 foreign key (client_rol_id) references tm_personas (rol_id);
alter table tm_automoviles add constraint FK604hap4xl02o3y0yo05cj393n foreign key (model_brand_id) references tm_modelos (brand_id);
alter table tm_modelos add constraint FK437xaojhj0q7ft5oeglhoeoxl foreign key (brand_id) references tm_marcas (id);
alter table tm_personas add constraint FKpwcqpamovfq31sv23xdf8d1pi foreign key (rol_id) references tm_roles (id);
